"""add shareholding tables

Revision ID: 04e12a99ff66
Revises: cbfd31d65d3f
Create Date: 2026-01-13 15:32:36.202390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04e12a99ff66'
down_revision: Union[str, Sequence[str], None] = 'cbfd31d65d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_sheet_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_stock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_sheet_dataset_company_id'), 'balance_sheet_dataset', ['company_id'], unique=False)
    op.create_index(op.f('ix_balance_sheet_dataset_id'), 'balance_sheet_dataset', ['id'], unique=False)
    op.create_table('cash_flow_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_stock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flow_dataset_company_id'), 'cash_flow_dataset', ['company_id'], unique=False)
    op.create_index(op.f('ix_cash_flow_dataset_id'), 'cash_flow_dataset', ['id'], unique=False)
    op.create_table('ratios_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_stock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratios_dataset_company_id'), 'ratios_dataset', ['company_id'], unique=False)
    op.create_index(op.f('ix_ratios_dataset_id'), 'ratios_dataset', ['id'], unique=False)
    op.create_table('share_holding_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_stock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_date', 'period_type')
    )
    op.create_index(op.f('ix_share_holding_period_company_id'), 'share_holding_period', ['company_id'], unique=False)
    op.create_table('share_holding_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['share_holding_period.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'key')
    )
    op.create_index(op.f('ix_share_holding_section_period_id'), 'share_holding_section', ['period_id'], unique=False)
    op.create_table('share_holding_section_child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['share_holding_section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_holding_section_child_section_id'), 'share_holding_section_child', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_holding_section_child_section_id'), table_name='share_holding_section_child')
    op.drop_table('share_holding_section_child')
    op.drop_index(op.f('ix_share_holding_section_period_id'), table_name='share_holding_section')
    op.drop_table('share_holding_section')
    op.drop_index(op.f('ix_share_holding_period_company_id'), table_name='share_holding_period')
    op.drop_table('share_holding_period')
    op.drop_index(op.f('ix_ratios_dataset_id'), table_name='ratios_dataset')
    op.drop_index(op.f('ix_ratios_dataset_company_id'), table_name='ratios_dataset')
    op.drop_table('ratios_dataset')
    op.drop_index(op.f('ix_cash_flow_dataset_id'), table_name='cash_flow_dataset')
    op.drop_index(op.f('ix_cash_flow_dataset_company_id'), table_name='cash_flow_dataset')
    op.drop_table('cash_flow_dataset')
    op.drop_index(op.f('ix_balance_sheet_dataset_id'), table_name='balance_sheet_dataset')
    op.drop_index(op.f('ix_balance_sheet_dataset_company_id'), table_name='balance_sheet_dataset')
    op.drop_table('balance_sheet_dataset')
    # ### end Alembic commands ###
