"""Added ChartDataSet table

Revision ID: 31c1884f8404
Revises: 0bf63e728631
Create Date: 2026-01-01 18:20:45.605913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31c1884f8404'
down_revision: Union[str, Sequence[str], None] = '0bf63e728631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_stock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_datasets_company_id'), 'chart_datasets', ['company_id'], unique=False)
    op.create_index(op.f('ix_chart_datasets_id'), 'chart_datasets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chart_datasets_id'), table_name='chart_datasets')
    op.drop_index(op.f('ix_chart_datasets_company_id'), table_name='chart_datasets')
    op.drop_table('chart_datasets')
    # ### end Alembic commands ###
