"""Added company sector field in CompanyStock

Revision ID: 7a69e15ff148
Revises: 02365045f7c6
Create Date: 2026-01-03 10:47:48.639311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a69e15ff148'
down_revision: Union[str, Sequence[str], None] = '02365045f7c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_stock', sa.Column('macro_economic_sector', sa.String(), nullable=True))
    op.add_column('company_stock', sa.Column('sector', sa.String(), nullable=True))
    op.add_column('company_stock', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('company_stock', sa.Column('basic_industry', sa.String(), nullable=True))
    op.create_index(op.f('ix_company_stock_basic_industry'), 'company_stock', ['basic_industry'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_stock_basic_industry'), table_name='company_stock')
    op.drop_column('company_stock', 'basic_industry')
    op.drop_column('company_stock', 'industry')
    op.drop_column('company_stock', 'sector')
    op.drop_column('company_stock', 'macro_economic_sector')
    # ### end Alembic commands ###
