"""add market deals

Revision ID: 7ef08c36dccc
Revises: 77cc38322338
Create Date: 2026-08-18 13:33:35.449919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef08c36dccc'
down_revision: Union[str, Sequence[str], None] = '77cc38322338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('deal_type', sa.String(length=30), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('buy_sell', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_stock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_deals_company_id'), 'market_deals', ['company_id'], unique=False)
    op.create_index(op.f('ix_market_deals_deal_type'), 'market_deals', ['deal_type'], unique=False)
    op.create_index(op.f('ix_market_deals_id'), 'market_deals', ['id'], unique=False)
    op.create_index(op.f('ix_market_deals_symbol'), 'market_deals', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_deals_trade_date'), 'market_deals', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_deals_trade_date'), table_name='market_deals')
    op.drop_index(op.f('ix_market_deals_symbol'), table_name='market_deals')
    op.drop_index(op.f('ix_market_deals_id'), table_name='market_deals')
    op.drop_index(op.f('ix_market_deals_deal_type'), table_name='market_deals')
    op.drop_index(op.f('ix_market_deals_company_id'), table_name='market_deals')
    op.drop_table('market_deals')
    # ### end Alembic commands ###
