"""added company table

Revision ID: 81be55b34b19
Revises: 21d1418e6979
Create Date: 2025-12-12 16:57:16.816071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81be55b34b19'
down_revision: Union[str, Sequence[str], None] = '21d1418e6979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('symbol', sa.String(length=150), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('company_name'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('symbol')
    )
    op.create_unique_constraint(None, 'users', ['mobile_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('company')
    # ### end Alembic commands ###
