"""added nse_code and bse_code in company table

Revision ID: 83805cca507a
Revises: cb62470a6aac
Create Date: 2026-02-04 16:24:18.475965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83805cca507a'
down_revision: Union[str, Sequence[str], None] = 'cb62470a6aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('bse_code', sa.String(length=15), nullable=True))
    op.add_column('company', sa.Column('nse_code', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'nse_code')
    op.drop_column('company', 'bse_code')
    # ### end Alembic commands ###
