"""Added StockPeerDataset table

Revision ID: abcc7730547c
Revises: 7a69e15ff148
Create Date: 2026-01-03 16:41:57.233215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abcc7730547c'
down_revision: Union[str, Sequence[str], None] = '7a69e15ff148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_peer_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('np_quarterly', sa.Float(), nullable=True),
    sa.Column('sales_quarterly', sa.Float(), nullable=True),
    sa.Column('quarterly_profit_var', sa.Float(), nullable=True),
    sa.Column('quarterly_sales_var', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_stock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_peer_datasets_company_id'), 'stock_peer_datasets', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_peer_datasets_id'), 'stock_peer_datasets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_peer_datasets_id'), table_name='stock_peer_datasets')
    op.drop_index(op.f('ix_stock_peer_datasets_company_id'), table_name='stock_peer_datasets')
    op.drop_table('stock_peer_datasets')
    # ### end Alembic commands ###
