"""Added company stock table

Revision ID: ac0d5c735ddc
Revises: 43f3a903e993
Create Date: 2025-12-30 15:55:30.146118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0d5c735ddc'
down_revision: Union[str, Sequence[str], None] = '43f3a903e993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True, comment='Company full name (e.g., Tata Steel Ltd)'),
    sa.Column('website', sa.String(), nullable=True, comment='Official company website'),
    sa.Column('bse_code', sa.String(), nullable=True, comment='BSE stock code'),
    sa.Column('nse_symbol', sa.String(), nullable=True, comment='NSE symbol'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_stock_bse_code'), 'company_stock', ['bse_code'], unique=False)
    op.create_index(op.f('ix_company_stock_name'), 'company_stock', ['name'], unique=False)
    op.create_index(op.f('ix_company_stock_nse_symbol'), 'company_stock', ['nse_symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_stock_nse_symbol'), table_name='company_stock')
    op.drop_index(op.f('ix_company_stock_name'), table_name='company_stock')
    op.drop_index(op.f('ix_company_stock_bse_code'), table_name='company_stock')
    op.drop_table('company_stock')
    # ### end Alembic commands ###
