"""Added QuarterlyResultDateset table

Revision ID: ae99bb518154
Revises: abcc7730547c
Create Date: 2026-01-05 10:58:36.295596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae99bb518154'
down_revision: Union[str, Sequence[str], None] = 'abcc7730547c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quarterly_result_dateset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_stock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarterly_result_dateset_company_id'), 'quarterly_result_dateset', ['company_id'], unique=False)
    op.create_index(op.f('ix_quarterly_result_dateset_id'), 'quarterly_result_dateset', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quarterly_result_dateset_id'), table_name='quarterly_result_dateset')
    op.drop_index(op.f('ix_quarterly_result_dateset_company_id'), table_name='quarterly_result_dateset')
    op.drop_table('quarterly_result_dateset')
    # ### end Alembic commands ###
