"""added nse_code in Company stock table

Revision ID: cb62470a6aac
Revises: 04e12a99ff66
Create Date: 2026-01-29 17:48:52.823896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb62470a6aac'
down_revision: Union[str, Sequence[str], None] = '04e12a99ff66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_stock', sa.Column('nse_code', sa.String(), nullable=True, comment='NSE stock code'))
    op.create_index(op.f('ix_company_stock_nse_code'), 'company_stock', ['nse_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_stock_nse_code'), table_name='company_stock')
    op.drop_column('company_stock', 'nse_code')
    # ### end Alembic commands ###
