"""Added ProfitLossDataset table

Revision ID: cbfd31d65d3f
Revises: ae99bb518154
Create Date: 2026-01-05 11:53:19.213694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbfd31d65d3f'
down_revision: Union[str, Sequence[str], None] = 'ae99bb518154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profit_loss_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_stock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profit_loss_dataset_company_id'), 'profit_loss_dataset', ['company_id'], unique=False)
    op.create_index(op.f('ix_profit_loss_dataset_id'), 'profit_loss_dataset', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profit_loss_dataset_id'), table_name='profit_loss_dataset')
    op.drop_index(op.f('ix_profit_loss_dataset_company_id'), table_name='profit_loss_dataset')
    op.drop_table('profit_loss_dataset')
    # ### end Alembic commands ###
