"""add stock_format key in stock table

Revision ID: ebd8d5949a0c
Revises: 3ee46acacce7
Create Date: 2026-05-19 15:36:05.231144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebd8d5949a0c'
down_revision: Union[str, Sequence[str], None] = '3ee46acacce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

result_format_enum = postgresql.ENUM(
    'standalone',
    'consolidated',
    name='result_format_enum',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_format_quarterly_result_dateset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_format', result_format_enum, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_stock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_format_quarterly_result_dateset_company_id'), 'custom_format_quarterly_result_dateset', ['company_id'], unique=False)
    op.create_index(op.f('ix_custom_format_quarterly_result_dateset_id'), 'custom_format_quarterly_result_dateset', ['id'], unique=False)
    op.add_column('company_stock', sa.Column('stock_format', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_stock', 'stock_format')
    op.drop_index(op.f('ix_custom_format_quarterly_result_dateset_id'), table_name='custom_format_quarterly_result_dateset')
    op.drop_index(op.f('ix_custom_format_quarterly_result_dateset_company_id'), table_name='custom_format_quarterly_result_dateset')
    op.drop_table('custom_format_quarterly_result_dateset')
    # ### end Alembic commands ###
